### ISSUE TITLE
String allocation

### ISSUE THREAD

**Issue by ttamttam** [yallop/ocaml-ctypes-inverted-stubs-example#11]
Hello,

suppose that I wrap a 1 function of an Ocaml library with something like this

```
  let () = I.internal "calcule" (string @-> returning string) Calcback.traite
```

The DLL/SO I'm generating from this has this function

```
  char* calcule(char* x17);
```

How/where is allocated the returned char *?

Should the caller free it?

Thanks

**Comment by yallop** [comment]
Good question!  For the moment I recommend not using `string` for this, since there are some subtleties around ownership and the garbage collector moving things around at inconvenient moments.  Basing things on bigarrays, if you can, is likely to make things easier.

Regarding freeing allocated memory, one approach is to register values as GC roots (see [the pull request that introduced roots to ctypes](https://github.com/ocamllabs/ocaml-ctypes/pull/318) for some details) before passing them to C, and expose a deallocation function that simply unregisters the roots, allowing the values to be collected in the next GC cycle.

**Comment by ttamttam** [comment]
Thanks for your answer.

I'm currently trying another solution: I'll let the client of the DLL manage buffer allocations.
The exported function would be something like:

```
int compute(char * question, char * buffer, size_t buffer_sz);
```

If the computed answer's length is lower than buffer_sz, the answer will be copied into buffer.
Else, the size of the answer is returned : the client has to increase the buffer's size and try again.

I now have to find out how/if i can do this directly with ocaml-ctypes, or if I'll have to come back to standard OCaml FFI.

Salutations

**Comment by yallop** [comment]
Having the caller allocate the buffer certainly simplifies things.

It should be straightforward to implement your interface in ctypes.  Here's an approach using bigarrays (untested):

``` ocaml
let compute question buffer buffer_sz =
  let int_sz = Unsigned.Size_t.to_int buffer_sz in
  let ba_buffer = Ctypes.(bigarray_of_ptr array1) int_sz Bigarray.char buffer in
  let computed_size = ... in
  if computed_size > int_sz then null
  else  ...
```

and here's an alternative approach using the Ctypes.CArray module:

``` ocaml
let compute question buffer buffer_sz =
  let int_sz = Unsigned.Size_t.to_int buffer_sz in
  let ba_buffer = Ctypes.CArray.from_ptr buffer int_sz in
  let computed_size = ... in
  if computed_size > int_sz then null
  else ...
```

**Comment by ttamttam** [comment]
Waou! Thanks for your examples. It helped a lot.

``` ocaml
(* char Ctypes.ptr -> Unsigned.Size_t.t -> char Ctypes.ptr -> Unsigned.Size_t.t -> int *)
let calcul_buffers question question_sz buffer buffer_sz =

  let ans = string_from_ptr question ~length:(Unsigned.Size_t.to_int question_sz)
                 |> Calcback.traite in
  let ans_sz = Bytes.length ans in

  let int_buffer_sz = Unsigned.Size_t.to_int buffer_sz in
  let ba_buffer = Ctypes.(bigarray_of_ptr array1) int_buffer_sz Bigarray.Char buffer in

  for i = 0 to pred (min int_buffer_sz ans_sz) do
    Bigarray.Array1.set ba_buffer i ans.[i]
  done;

  ans_sz
```

Instead of the for-loop, I had the idea to use `Bigarray.Array1.blit`, but I could not find out how I would build another `(char, Bigarray.int8_unsigned_elt, Bigarray.c_layout) Bigarray.Array1.t` from ans:string.

Thanks again for taking the time to answer my questions.

**Comment by yallop** [comment]
> Instead of the for-loop, I had the idea to use Bigarray.Array1.blit, but I could not find out how I would build another (char, Bigarray.int8_unsigned_elt, Bigarray.c_layout) Bigarray.Array1.t from ans:string.

If you happen to be using Core already, you can use [`blit_string_bigstring`](https://ocaml.janestreet.com/ocaml-core/109.24.01/doc/core/Bigstring.html#VALblit_string_bigstring) to blit `ans` directly to the output buffer.

If you don't mind allocating an intermediate bigarray value then you can use something like this instead (untested):

``` ocaml
bigarray_of_ptr array1 ans_sz Bigarray.char (coerce string (ptr char) s)
```

**Comment by ttamttam** [comment]
I missed the coercion step.

Thank you.

Do you think the examples above may be of interest for others? I do not
know where they could be put for this? I you say so, I can move them to
some other place.

**Comment by yallop** [comment]
Yes, they could be of interest to others.  Either a page on the [wiki](https://github.com/ocamllabs/ocaml-ctypes/wiki) or a post to the [mailing list](http://lists.ocaml.org/listinfo/ctypes) would make them easier to find.

**Comment by yallop** [comment]
Here's @ttamttam's mail to the list: http://lists.ocaml.org/pipermail/ctypes/2015-December/000192.html
