### ISSUE TITLE
Optional Arguments in module definition

### ISSUE THREAD

**Issue by kevallakhani95** [yallop/ocaml-ctypes-inverted-stubs-example#14]
I have a bindings file like:
```
open Ctypes
let build ?(i=1) ?(j=2) () = 
i + j

module Bindings(I: Cstubs_inverted.INTERNAL) =
struct
  let _ = I.internal "build" (?(i:int) @-> ?(j:int) @-> unit @-> returning int) build
end
```
When trying to build, this gives me a syntax error at the first "?".

Could you please tell me what this might be for? 

Thanks.

**Comment by yallop** [comment]
Unfortunately, optional arguments aren't supported here, and I don't think it's possible to support them.

Although the second argument to `I.internal` looks like a type, it's actually just a value -- more precisely, it's an operator that takes two arguments

```ocaml
val (@->) :  'a typ -> 'b fn -> ('a -> 'b) fn
```

The arguments to `@->` are just values, too, so It's not possible to pass labeled argument specifications in place of the arguments.

Something like the following (testing) should do what you need:

```ocaml
open Ctypes
let build ?(i=1) ?(j=2) () = 
   i + j

module Bindings(I: Cstubs_inverted.INTERNAL) =
struct
  let () = I.internal "build" (int @-> int @-> unit @-> returning int) 
     (fun i j () -> build ~i ~j ())
end
```

**Comment by kevallakhani95** [comment]
Hi, 
Thanks @yallop for a prompt response. Actually what I am trying to do is that build a function that can take optional arguments and create an interface for that using cstubs_inverted. I want to pass only some arguments from a C++ file to the bindings via the interface. Anyway, Thanks a ton! :)
