### ISSUE TITLE
Please specify a license

### ISSUE THREAD

**Issue by dmbaturin** [yallop/ocaml-ctypes-inverted-stubs-example#15]
Thanks for your work, it would take me ages to figure out by myself!

I assume you are fine with reusing this code, but could you please specify a license, to make it obvious what the reuse conditions are.

**Comment by yallop** [comment]
Yes, I hope that people find this code useful and reuse it elsewhere.  #16 adds the liberal MIT license.  (If there's some reason that's not suitable for your needs, let me know.)

**Comment by dmbaturin** [comment]
MIT is perfect, for everyone's needs I think, not just mine.
