### ISSUE TITLE
Is it supposed to be doable on Windows?

### ISSUE THREAD

**Issue by ttamttam** [yallop/ocaml-ctypes-inverted-stubs-example#7]
The first try failed, because of the classical problems of windows (generate.exe instead of generate)…

```
~/ocaml-ctypes-inverted-stubs-example $ make
ocamlfind opt -c -o _build/lib/bindings.cmx -I _build/generated -I _build/lib -package xmlm,ctypes.stubs,ctypes.foreign lib/bindings.ml
ocamlfind opt -c -o _build/stub_generator/generate.cmx -I _build/generated -I _build/lib -package xmlm,ctypes.stubs,ctypes.foreign stub_generator/generate.ml
ocamlfind opt -o _build/generate -linkpkg -package xmlm,ctypes.stubs,ctypes.foreign _build/lib/bindings.cmx _build/stub_generator/generate.cmx
** Error: Sys_error("_build/generate: No such file or directory")
File "caml_startup", line 1:
Error: Error during linking
Makefile:43: recipe for target '_build/generate' failed
make: *** [_build/generate] Error 2
```

OK. Let's try another way:

```
ocamlbuild -use-ocamlfind -pkgs ctypes.stubs,ctypes.foreign,xmlm -Is stub_generator,lib stub_generator/generate.native -- _build/generated
mkdir 'C:\cygwin\home\vagrant\ocaml-ctypes-inverted-stubs-example\_build'
mkdir stub_generator
''ocamlfind ocamldep -package xmlm -package ctypes.foreign -package ctypes.stubs -modules stub_generator/generate.ml > stub_generator/generate.ml.depends
mkdir lib
''ocamlfind ocamldep -package xmlm -package ctypes.foreign -package ctypes.stubs -modules lib/bindings.ml > lib/bindings.ml.depends
''ocamlfind ocamlc -c -package xmlm -package ctypes.foreign -package ctypes.stubs -I lib -I stub_generator -o lib/bindings.cmo lib/bindings.ml
''ocamlfind ocamlc -c -package xmlm -package ctypes.foreign -package ctypes.stubs -I stub_generator -I lib -o stub_generator/generate.cmo stub_generator/generate.ml
''ocamlfind ocamlopt -c -package xmlm -package ctypes.foreign -package ctypes.stubs -I lib -I stub_generator -o lib/bindings.cmx lib/bindings.ml
''ocamlfind ocamlopt -c -package xmlm -package ctypes.foreign -package ctypes.stubs -I stub_generator -I lib -o stub_generator/generate.cmx stub_generator/generate.ml
''ocamlfind ocamlopt -linkpkg -package xmlm -package ctypes.foreign -package ctypes.stubs lib/bindings.cmx stub_generator/generate.cmx -o stub_generator/generate.native
Fatal error: exception Ctypes_static.Unsupported("FFI_DEFAULT_ABI")
```

Thanks

**Comment by yallop** [comment]
I'd certainly like this to work on Windows, and welcome pull requests to improve things.  We should also set up AppVeyor to ensure that the Windows build continues to work.

The `FFI_DEFAULT_ABI` error suggests that something's wrong with the ocaml-ctypes build.  How did you install ctypes?  Are you able to run the ctypes tests (by typing `make all test`) in the ctypes directory?

**Comment by ttamttam** [comment]
```
 [...] welcome pull requests to improve things. [...]
```

If only I had the skills to… But I'm trying to understand and help if possible.

```
The FFI_DEFAULT_ABI error suggests that something's wrong with the ocaml-ctypes build.
How did you install ctypes? Are you able to run the ctypes tests (by typing make all test) in the ctypes directory?
```

I had to use `--disable-shared --enable-static` in order to have `libffi` compiled, following: [ocaml-ctypes' appveyor recipe](https://github.com/ocamllabs/ocaml-ctypes/blame/master/appveyor/build.sh#L63). If I understand correctly, this [thread](https://github.com/ocamllabs/ocaml-ctypes/issues/198), a static version of `libffi` is to be used. Maybe, I did not follow carefully enough the appveyor recipe to compile `ocaml-ctypes` ([here](tps://ci.appveyor.com/project/yallop/ocaml-ctypes/build/1.0.22/job/gtfobmaf4y883y7i)), since in my case: `date-cmd.native` works, but `date.native` does not.

I'll try again and will come back here to give feedback.

Thanks

**Comment by ttamttam** [comment]
OK. My bad. It works ( :-) ), but I had to modify the Makefiles.

I created a pull request : https://github.com/yallop/ocaml-ctypes-inverted-stubs-example/pull/8

Salutations
